添加自定义gravatar镜像的环境变量
bs-community/blessing-skin-plugins pull request #217
Opened 2024-08-07 05:31 UTC by AkariRin

鉴于gravatar在国内访问受阻的问题，添加了`GRAVATAR_REGISTRY`这一环境变量，可自定义gravatar源

环境变量示例：
`GRAVATAR_REGISTRY=https://gravatar.loli.net/avatar/`

2024-08-07 05:35 UTC, mochaaP commented
最好提供一個默認值。

2024-08-07 05:36 UTC, mochaaP requested changes

2024-08-07 05:36 UTC, mochaaP commented on plugins/gravatar/bootstrap.php
> +        $registry = env('GRAVATAR_REGISTRY');
^ 這裡增加默認值。

2024-08-07 05:57 UTC, gxres042 commented on plugins/gravatar/bootstrap.php
> +        $registry = env('GRAVATAR_REGISTRY');
```suggestion
        $registry = env('GRAVATAR_REGISTRY', "https://www.gravatar.com/avatar/$hashed");
```

2024-08-07 08:32 UTC, AkariRin commented
@mochaaP 已添加萝莉源作为默认值
@g-plane 我不是写php的，但我可以尝试一下写个配置页面，类似于gtag插件那样的

2024-08-07 09:16 UTC, mochaaP commented
> 已添加萝莉源作为默认值

麻煩使用官方源作為默認值。
要提供更多選擇，可以寫在注釋中。

2024-08-07 12:14 UTC, AkariRin commented
@mochaaP 已经在[f6cc046](https://github.com/bs-community/blessing-skin-plugins/pull/217/commits/f6cc046b7f0bb4f25768471aed8eee7333e45d10)这次提交中更改了

2024-08-07 15:16 UTC, mochaaP approved these changes

2024-08-11 16:32 UTC, AkariRin commented
@gxres042 可否approve一下，合并需要两个reviewer approval

2024-08-11 22:28 UTC, gxres042 approved these changes

2024-08-16 11:46 UTC, merged